# SmartHome IoT Simulator Configuration
broker:
  host: 4108a3db64d742a5963319148924c7fd.s1.eu.hivemq.cloud
  port: 8883
  user: Soblito
  password: "j'41m3HiveMQ"

user_id: e04586e5-bcc2-41db-a922-9be3d1367c63

devices:
