[plexus.core]
load ${maven.home}/lib/*

[plexus.utils]
load ${maven.home}/lib/maven-*.jar

[plexus.artifact.manager]
load ${maven.home}/lib/wagon-*.jar

[plexus.plugin.manager]
load ${maven.home}/lib/maven-plugin-api-*.jar
