spring:
  application:
    name: smart-home-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:smarthome}
    username: ${DB_USER:smarthome}
    password: ${DB_PASSWORD:smarthome}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}

server:
  port: 8081

mqtt:
  host: ${MQTT_HOST:localhost}
  port: ${MQTT_PORT:8883}
  client-id: ${MQTT_CLIENT_ID:smarthome-backend}
  username: ${MQTT_USER:}
  password: ${MQTT_PASSWORD:}
  topic:
    telemetry-wildcard: "home/+/device/+/telemetry"
    status-wildcard: "home/+/device/+/status"
    command-ack-wildcard: "home/+/device/+/command/ack"

jwt:
  secret: ${JWT_SECRET:change-me-in-production-must-be-at-least-256-bits-long}
  access-token-expiration-ms: 900000       # 15 minutes
  refresh-token-expiration-ms: 604800000   # 7 jours

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200}
